### PR TITLE
feat(configuration): adds detail_case config

### PR DESCRIPTION
**Pull request by anaice**
#59

Case configuration for detail when operation is `:dispatch_event`. 
Options for `detail_case`:
- camel (default)
- pascal
- snake
- kebab
- keep (keeps original)

### CODE REVIEW

**Comment by leastbad** [comment]
Hey @anaice!

I finally had a chance to review. There are a few things that we're going to have to change up, because now that I see the implementation, I'm no longer convinced that a configuration is the best approach for this problem.

First thing first, let's start by temporarily forgetting my last statement and looking at how you did the config. You brought in a dependency to manage a config file, but CableReady already has support for an initializer. This is why I mentioned that it was important to consult #47. Instead of using anyway_config, we can just add additional settings to the initializer.

I also don't think we should attempt to provide pascal or kebab at this time. camelCase is clearly the default, and I agree that there's value in offering snake_case, too. So this means that however we attack this, we can reduce it to a ternary with the pseudocode:

`operations.deep_transform_keys! { |key| camel ? key.to_s.camelize(:lower) :  key.to_s.underscore }`

Here's where I'm at with this: I feel awkward about setting a precedent for individual operations, which on the server are generally treated equally. We should expect that people might want other methods to return detail objects that have snake case as well.

My sense is that if someone wants to send a broadcast with snake case, we should let them set that as a parameter on a broadcast. There is already a precedent for this; both `broadcast` and `broadcast_to` methods have an optional named parameter called `clear` that gets passed to the channel on channels.rb lines 56 and 66 as a boolean.

What I think makes more sense is to do this in channels.rb:
```rb
    def broadcast(*identifiers, clear: true, camel: true)
      @channels.values
        .reject { |channel| identifiers.any? && identifiers.exclude?(channel.identifier) }
        .select { |channel| channel.identifier.is_a?(String) }
        .tap do |channels|
          channels.each { |channel| @channels[channel.identifier].broadcast(clear: clear, camel: camel) }
          channels.each { |channel| @channels.except!(channel.identifier) if clear }
        end
    end

    def broadcast_to(model, *identifiers, clear: true, camel: true)
      @channels.values
        .reject { |channel| identifiers.any? && identifiers.exclude?(channel.identifier) }
        .reject { |channel| channel.identifier.is_a?(String) }
        .tap do |channels|
          channels.each { |channel| @channels[channel.identifier].broadcast_to(model, clear: clear, camel: camel) }
          channels.each { |channel| @channels.except!(channel.identifier) if clear }
        end
    end
```
and then in channel.rb:
```rb
    def broadcast(clear:, camel:)
      operations.select! { |_, list| list.present? }
      operations.deep_transform_keys! { |key| camel ? key.to_s.camelize(:lower) :  key.to_s.underscore }
      ActionCable.server.broadcast identifier, "cableReady" => true, "operations" => operations
      reset if clear
    end

    def broadcast_to(model, clear:, camel:)
      operations.select! { |_, list| list.present? }
      operations.deep_transform_keys! { |key| camel ? key.to_s.camelize(:lower) :  key.to_s.underscore }
      identifier.broadcast_to model, "cableReady" => true, "operations" => operations
      reset if clear
    end
```

This would allow you as developer to do something like:
```rb
cable_ready["stream"].dispatch_event(detail: {user_name: "leastbad"}, selector: "body", name: "my_event")
cable_ready.broadcast(camel: false)
```
and this would allow the granular ability to override any operation with snake case details on a per-broadcast basis.

What do you think, @hopsoft?

**Comment by leastbad** [comment]
Late thought: another variation on this could be to make the falsy condition simply not do any modifications, so the developer could have direct control of exactly what gets sent down the wire. This might actually be an even better approach.

channel.rb:
```rb
    def broadcast(clear:, camel:)
      operations.select! { |_, list| list.present? }
      operations.deep_transform_keys! { |key| key.to_s.camelize(:lower) } if camel
      ActionCable.server.broadcast identifier, "cableReady" => true, "operations" => operations
      reset if clear
    end

    def broadcast_to(model, clear:, camel:)
      operations.select! { |_, list| list.present? }
      operations.deep_transform_keys! { |key| key.to_s.camelize(:lower) } if camel
      identifier.broadcast_to model, "cableReady" => true, "operations" => operations
      reset if clear
    end
```

**Comment by anaice** [comment]
> Hey @anaice!
> 

Hey @leastbad!
First of all I would like to thank you for your time helping me with this. 🙏

> I finally had a chance to review. There are a few things that we're going to have to change up, because now that I see the implementation, I'm no longer convinced that a configuration is the best approach for this problem.
> 
In my opinion your original idea of ​​configuration is good, because generally when you want a case pattern the application will stick to it. The best option in my opinion would be the configuration and also an optional override per-broadcast operation. But I agree that we can do with the parameter only.

> First thing first, let's start by temporarily forgetting my last statement and looking at how you did the config. You brought in a dependency to manage a config file, but CableReady already has support for an initializer. This is why I mentioned that it was important to consult #47. Instead of using anyway_config, we can just add additional settings to the initializer.
> 
Yes. Sorry about that

> I also don't think we should attempt to provide pascal or kebab at this time. camelCase is clearly the default, and I agree that there's value in offering snake_case, too. So this means that however we attack this, we can reduce it to a ternary with the pseudocode:
> 
> `operations.deep_transform_keys! { |key| camel ? key.to_s.camelize(:lower) : key.to_s.underscore }`
> 
I understand. I just thought that if we were to give the config  we could have more options, giving more control to the developer. I also think that if we are going to use the ternary we should choose not to make any changes to the keys (the "keep" option of the PR). This way the event detail payload will not be changed: if the detail has `user_id` or `myUser_Id` the format will be maintained.


> Here's where I'm at with this: I feel awkward about setting a precedent for individual operations, which on the server are generally treated equally. We should expect that people might want other methods to return detail objects that have snake case as well.
> 
> My sense is that if someone wants to send a broadcast with snake case, we should let them set that as a parameter on a broadcast. There is already a precedent for this; both `broadcast` and `broadcast_to` methods have an optional named parameter called `clear` that gets passed to the channel on channels.rb lines 56 and 66 as a boolean.
> 
> What I think makes more sense is to do this in channels.rb:
> 
> ```ruby
>     def broadcast(*identifiers, clear: true, camel: true)
>       @channels.values
>         .reject { |channel| identifiers.any? && identifiers.exclude?(channel.identifier) }
>         .select { |channel| channel.identifier.is_a?(String) }
>         .tap do |channels|
>           channels.each { |channel| @channels[channel.identifier].broadcast(clear: clear, camel: camel) }
>           channels.each { |channel| @channels.except!(channel.identifier) if clear }
>         end
>     end
> 
>     def broadcast_to(model, *identifiers, clear: true, camel: true)
>       @channels.values
>         .reject { |channel| identifiers.any? && identifiers.exclude?(channel.identifier) }
>         .reject { |channel| channel.identifier.is_a?(String) }
>         .tap do |channels|
>           channels.each { |channel| @channels[channel.identifier].broadcast_to(model, clear: clear, camel: camel) }
>           channels.each { |channel| @channels.except!(channel.identifier) if clear }
>         end
>     end
> ```
> 
> and then in channel.rb:
> 
> ```ruby
>     def broadcast(clear:, camel:)
>       operations.select! { |_, list| list.present? }
>       operations.deep_transform_keys! { |key| camel ? key.to_s.camelize(:lower) :  key.to_s.underscore }
>       ActionCable.server.broadcast identifier, "cableReady" => true, "operations" => operations
>       reset if clear
>     end
> 
>     def broadcast_to(model, clear:, camel:)
>       operations.select! { |_, list| list.present? }
>       operations.deep_transform_keys! { |key| camel ? key.to_s.camelize(:lower) :  key.to_s.underscore }
>       identifier.broadcast_to model, "cableReady" => true, "operations" => operations
>       reset if clear
>     end
> ```
> 
> This would allow you as developer to do something like:
> 
> ```ruby
> cable_ready["stream"].dispatch_event(detail: {user_name: "leastbad"}, selector: "body", name: "my_event")
> cable_ready.broadcast(camel: false)
> ```
> 
> and this would allow the granular ability to override any operation with snake case details on a per-broadcast basis.
> 
Even though I still prefer configuration. I’m ok with a per-broadcast option. 

One important thing: we want to change only the detail payload for :dispatch_event operations, so the transformation of keys must be done differently. 
Initially I just used deep_transform_keys, but this changes the whole object graph which ended up breaking the JS part of the lib, as it uses camelCase, for example: dispatch_event does not work, dispatchEvent works. Therefore, the entire object must be kept camel, only the content of the detail must be configurable. That's why we have:

```ruby
# lib/cable_ready/channel.rb
#...
   def broadcast(clear)
      operations.select! { |_, list| list.present? }
      # operations.deep_transform_keys! { |key| key.to_s.camelize(:lower) }
      handle_operations_keys! operations
      ActionCable.server.broadcast identifier, "cableReady" => true, "operations" => operations
      reset if clear
    end

    def handle_operations_keys!(operations)
      dispatch_operations = operations.extract! :dispatch_event
      operations.deep_transform_keys! { |key| key.to_s.camelize(:lower) }

      if dispatch_operations.key? :dispatch_event
        dispatch_operations[:dispatch_event].each do |event|
          event[:detail]&.deep_transform_keys! { |key| case_for_detail(key) } #CableReady.config
          event.transform_keys!{ |key| key.to_s.camelize(:lower) }
        end
        dispatch_operations.transform_keys!{ |key| key.to_s.camelize(:lower) }
        operations.merge! dispatch_operations
      end
    end

    def case_for_detail(key)
      case config.detail_case
      when "snake"
        key.to_s.underscore
      when "pascal"
        key.to_s.camelize
      when "kebab"
        key.to_s.dasherize
      when "camel"
        key.to_s.camelize(:lower)
      when "keep" #keeps original
        key.to_s
      else
        key.to_s.camelize(:lower)
      end
    end
#...
```
I've a running application using CableReady with the PR version:
object-graph-js-evt-cable-ready

`operations.deep_transform_keys!` all way down will result in dispatch_event

> What do you think, @hopsoft?

@leastbad and @hopsoft  I will follow your discussion on this.
Thanks again for your time and for this excellent gem!

**Comment by anaice** [comment]
> Late thought: another variation on this could be to make the falsy condition simply not do any modifications, so the developer could have direct control of exactly what gets sent down the wire. This might actually be an even better approach.
> 
> channel.rb:
> 
> ```ruby
>     def broadcast(clear:, camel:)
>       operations.select! { |_, list| list.present? }
>       operations.deep_transform_keys! { |key| key.to_s.camelize(:lower) } if camel
>       ActionCable.server.broadcast identifier, "cableReady" => true, "operations" => operations
>       reset if clear
>     end
> 
>     def broadcast_to(model, clear:, camel:)
>       operations.select! { |_, list| list.present? }
>       operations.deep_transform_keys! { |key| key.to_s.camelize(:lower) } if camel
>       identifier.broadcast_to model, "cableReady" => true, "operations" => operations
>       reset if clear
>     end
> ```

I agree with this. The developer is responsible for the detail payload.

**Comment by leastbad** [comment]
Ahh, that's what I get for proposing code in a textarea! Good catch... so, more code would be required to modify only the details hash.

I still think that we can vastly simplify things.

camelCase is the default and will remain so. Not only are we not planning to break existing deployments and functionality, JS devs do expect to work with camelCase values. Kebab case values aren't even valid in JS and Pascal case values are, like in Ruby, used for class names. Snake case values are handy for Rails devs, so again, I have your back on being able to opt-in.

I do have to defer to @hopsoft regarding whether he'd be more preferential to a global configuration or a named parameter to broadcast.

**Comment by anaice** [comment]
@leastbad 
You're right. Taking a step back I really think we can simplify things. Only a configuration and/or per-broadcast parameter will work: `camelize_detail`, a falsy condition to simply not do any modifications.
I believe that the detail payload should be chosen by the developer. But camel case is mandatory to maintain backwards compatibility, as you said it must be the default.

**Comment by leastbad** [comment]
Hey @anaice! Hope that you're good.

Lots has changed since this PR was submitted, and it's safe to say that we're probably not going to be accepting this change. Still, we sincerely appreciate the contribution, regardless.

**Pull request closed without merging**
