### PR TITLE
Add support for pushState

### PR DESCRIPTION
**Pull request by hopsoft**

### CODE REVIEW

**Review by leastbad — COMMENTED** [review]
While I think this change is positive, I'm always a bit confounded when folks roll massive structural overhaul into a single commit on a relatively unrelated feature proposal PR. This is open source, not the US Congress, damnit!

**Comment by hopsoft** [comment]
I almost opt'd to skip the refactor, but then figured... what the hell.

**Comment by leastbad** [comment]
I left comments on Discord that I hope are not lost:

https://discordapp.com/channels/629472241427415060/683317077423292582/750930958718468136

as for the "what the hell", I agreed last night but incidentally and with some irony, I want to make a PR and now whatever I submit will be out of date. That's annoying. 👅

**Comment by leastbad** [comment]
Que?

**Pull request closed without merging**
